hive:
  hosts:
    hive-proxmox:
      ansible_user: root
      ansible_password: "{{ proxmox_ansible_password }}"
      ansible_host: 192.168.178.66
      ansible_python_interpreter: /usr/bin/python3.13
      proxmox_host: hive
    hive02-proxmox:
      ansible_user: root
      ansible_password: "{{ proxmox02_ansible_password }}"
      ansible_host: 192.168.178.67
      ansible_python_interpreter: /usr/bin/python3.13
      proxmox_host: hive02
